default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  host: localhost
  username: root
  password: diablo12
  reconnect: true
  socket: <%= ['/tmp/mysqld.sock',
               '/tmp/mysql.sock',
               '/var/run/mysqld/mysqld.sock',
               '/var/lib/mysql/mysql.sock'].detect{|socket| File.exist?(socket) } %>

development:
  <<: *default
  database: guchiro_development

test:
  <<: *default
  database: guchiro_test

staging:
  <<: *default
  database: guchiro_staging

production:
  <<: *default
  database: guchiro_production
