# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 21f5500dd3ea79f01fde7a531bb4b9146aa23091f6898f06dc6ca561bfa5d9fa482b9f958ee8be341e15b49e030d2f37c073de1c7ad43aa2fd15a0b97aca9685

test:
  secret_key_base: e72354b4a4bc234371918694a26f9d114f77b4a26e514ce30ee79309428690fe036115235b1e77f4811c0523f175d1465f97038c24bd4b7cff372af22f41e02b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
